### ISSUE TITLE
Supported PHP versions are outdated

### ISSUE THREAD

**Issue by dmolineus** [phpcq/travis-configuration-check#1]
I started to update my build matrix to test against PHP 7.2 as well. Travis already supports it.
Unfortunately travis-configuration-check claims it is not supported.

I tried to run the `update-constants.php`. This is broken as well, as the travis docs has moved and there is no list of supported PHP versions anymore.

**Comment by discordier** [comment]
DOH! The update scripts was a hack...
I guess we need to update manually.

we also have some further adjustments in develop, maybe you would be so kind to alter the PHP versions and test the develop with them so we could release 1.3?

**Comment by dmolineus** [comment]
PHP 7.3. is officially released now (Release candidate was supported sometimes ago in travis anyway). I  added support for it in the hotfix/1.2.3 branch. Or should we bump minor release for it?

**Comment by discordier** [comment]
IMHO we should fix it as patch.
Testing is a "rolling release" and therefore we should add this as soon as it becomes available.

Therefore good to go as 1.2.3 - tag at will.

**Comment by discordier** [comment]
Implemented in 82cd442babfbf78c0309c81299aa57e2303b0bec
